#for dynamixel
L_THUMB_JOINT0:
  ID: 7
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 740
L_THUMB_JOINT1:
  ID: 8
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 740
L_INDEX_JOINT0:
  ID: 9
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: 341
L_INDEX_JOINT1:
  ID: 10
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: 341
L_MIDDLE_JOINT0:
  ID: 11
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: 341
L_LOCK_JOINT0:
  ID: 12
  Return_Delay_Time: 0
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: 341
