#for dynamixel
#x:direction of index and middle finger
L_THUMB_JOINT0:
  ID: 7
  Return_Delay_Time: 50
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: 2048
L_THUMB_JOINT1:
  ID: 8
  Return_Delay_Time: 50
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: -2048
L_INDEX_JOINT0:
  ID: 9
  Return_Delay_Time: 50
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: -2390
L_INDEX_JOINT1:
  ID: 10
  Return_Delay_Time: 50
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: -2048
L_MIDDLE_JOINT0:
  ID: 11
  Return_Delay_Time: 50
  Operating_Mode: 5
  Drive_Mode: 1
  Current_Limit: 740
  Homing_Offset: 2048
L_LOCK_JOINT0:
  ID: 12
  Return_Delay_Time: 50
  Operating_Mode: 5
  Current_Limit: 740
  Homing_Offset: -1070
##ID 7: 0~120
##ID 8: 0~100
##ID 9:-120~0
##ID 10: -100~90
##ID 11:-120~0
##ID 12:  0~14
